### ISSUE TITLE
RangeSlider labels cut off when used with Napari

### ISSUE THREAD

**Issue by multimeric** [pyapp-kit/magicgui#575]
**Describe the bug**
When a `RangedSlider` is used inside Napari, many of the numbers appear to be cut off. See image 1.

**To Reproduce**
I have a repo that reproduces this here: https://github.com/multimeric/napari-magicgui-cutoff.

In brief, all you need to reproduce this is a Napari widget defined like this:
```python
from magicgui import magic_factory

@magic_factory(x={'widget_type': 'RangeSlider', 'max': 50})
def example_magic_widget(x: tuple[int, int]):
    print(f"you have selected {x}")
```

**Expected behavior**
I expect none of the labels to be cut off (see image 2)

**Screenshots**
![Screen Shot 2023-08-17 at 2 38 11 pm](https://github.com/pyapp-kit/magicgui/assets/5019367/c24e0131-871a-45cf-aa9b-2267b695af6a)

Compare this with a non-Napari version of a similar `magicgui` function:
![Screen Shot 2023-08-17 at 2 41 49 pm](https://github.com/pyapp-kit/magicgui/assets/5019367/f329a6d0-1475-4d82-8c34-54acd8daa0a8)

**Environment (please complete the following information):**
 - OS: MacOS 12.6 Monterey
 - backend: Qt 5.15.2
 - magicgui version: 0.7.2

**Comment by tlambert03** [comment]
thanks for the clear issue @multimeric.  This is going to have to be solved on the napari side though (or possibly with communication via napari and superqt), since it's an issue with napari's style sheets.  For example, if I clear the napari stylesheet after adding it to napari:
```python
wdg = example_magic_widget()
viewer = napari.Viewer()
viewer.window.add_dock_widget(wdg)
viewer.window._qt_window.setStyleSheet("")
napari.run()
```

then the slider looks fine:
<img width="311" alt="Screen Shot 2023-08-17 at 7 11 39 AM" src="https://github.com/pyapp-kit/magicgui/assets/1609449/64b7a28b-c8ea-4523-8506-24f46e110005">

so, it's possible that the napari style sheet is making some assumptions?

transferring this issue to napari.

**Comment by tlambert03** [comment]
oh sorry, looks like I can't transfer across orgs.  so I'll open an issue for you at napari

**Comment by tlambert03** [comment]
see https://github.com/napari/napari/issues/6160
