### ISSUE TITLE
docs: pymdownx.inlinehilite (via mkdocs-gallery) breaking autorefs

### ISSUE THREAD

**Issue by tlambert03** [pyapp-kit/magicgui#584]
Hey @GenevieveBuckley, 

I just noticed an unfortunate problem with mkdocs-gallery that might require a reversion of #571 .  Any mkdocstrings link that uses backticks for formatting like ``[`magicgui.some.class`][]`` (which is a lot of them) breaks when mkdocs gallery is enabled, even if it's a file that has nothing to do with an example.  

For example on the [main widgets page](https://pyapp-kit.github.io/magicgui/widgets/):

with mkdocs-gallery enabled:

<img width="705" alt="Screen Shot 2023-09-07 at 6 42 58 AM" src="https://github.com/pyapp-kit/magicgui/assets/1609449/6c7a338c-1757-42fb-b402-2f1e1cfe27c0">

without mkdocs-gallery enabled:

<img width="707" alt="Screen Shot 2023-09-07 at 6 43 32 AM" src="https://github.com/pyapp-kit/magicgui/assets/1609449/f59bb5e5-0c92-4f94-805a-0d65848ca3a0">

**Comment by GenevieveBuckley** [comment]
Oh noooo 😢

**Comment by GenevieveBuckley** [comment]
I looked at this problem more today.

1. I have a PR open to fix the immediate issue in this repository https://github.com/pyapp-kit/magicgui/pull/587
2. I tried figuring out the root cause of the issue, but wasn't able to reproduce it with a more minimal example repository.

See here for the example repository: https://github.com/GenevieveBuckley/test-mkdocs-links 
Running mkdocs serve on that doesn't break the hyperlink in the same way we saw here in magicgui. 

I originally thought there might be some bad interaction between the `mkdocstrings` and `mkdocs-gallery` plugins, but I didn't see that happening here. It's possible there is some sort of funky interaction going on when you make the configuration file more complicated & add more plugins (or add python gallery example scripts, or scripts involving pyqt, etc., etc.). I wonder if it's possibly the `gallery_conf.py` file, too?

I don't have any more time to dedicate to this, but wanted to share what I had anyway.

**Comment by tlambert03** [comment]
Thanks so much @GenevieveBuckley, I appreciate you taking a look and the minimal repo is very useful.


I'll take it from here and see what I can figure out

**Comment by tlambert03** [comment]
ok, I was able to determine that this isn't an issue with mkdocs-gallery per se, but rather the addition of `pymdownx.inlinehilite` to the markdown_extensions (which mkdocs gallery does implicitly).  That breaks mkdocs-autorefs when using code backticks

With this mkdocs config:
```yml
site_name: My Docs
markdown_extensions:
  - pymdownx.inlinehilite
plugins:
  - mkdocstrings
```

I can reproduce the issue on a tiny little docs site:

This breaks:

```md
# Welcome to MkDocs

[`thing.MyClass`][]

::: thing.MyClass

```

whereas using `[thing.MyClass][]` works fine.

**Comment by tlambert03** [comment]
related issue on autorefs here: https://github.com/mkdocstrings/autorefs/issues/34

**Comment by GenevieveBuckley** [comment]
You narrowed that down impressively fast, nice work!
